# Generated by Django 3.2.4 on 2021-07-04 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prato', models.CharField(max_length=150)),
                ('tamanho', models.CharField(max_length=11)),
                ('categoria', models.CharField(choices=[(None, 'Desconhecido'), ('Árabe', 'Arabe'), ('Oriental', 'Oriental'), ('Brasileira', 'Brasileira'), ('Mediterrânea', 'Mediterranea'), ('Contemporânea', 'Contemporanea')], default='Desconhecido', max_length=15)),
                ('ingredientes', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='prato')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cardapio',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mesa', models.IntegerField(unique=True)),
                ('quant_cadeiras', models.IntegerField()),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField(default=None, null=True)),
                ('tempo', models.IntegerField(verbose_name='Tempo (min)')),
                ('quant_pessoas', models.IntegerField()),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.mesa')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
