# Generated by Django 3.2.4 on 2021-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tempo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora1',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora2',
            field=models.TimeField(default=None),
        ),
    ]
