# Generated by Django 3.2.4 on 2021-06-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210623_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='categoria',
        ),
    ]
