# Generated by Django 3.2.4 on 2021-07-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210704_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='hora1',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='quant_cadeiras',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora2',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='quant_pessoas',
        ),
    ]
