# Generated by Django 3.2.3 on 2021-06-11 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cardapio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mesa', models.IntegerField()),
                ('quant_cadeiras', models.IntegerField()),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=13)),
                ('ocasiao', models.CharField(max_length=60)),
                ('num_pessoas', models.IntegerField()),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.AlterModelTable(
            name='cardapio',
            table='cardapio',
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('id_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mesa')),
                ('id_reservas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reserva')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
    ]
