# Generated by Django 3.2.4 on 2021-06-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cardapio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='categoria',
            field=models.CharField(choices=[('Árabe', 'Arabe'), ('Oriental', 'Oriental'), ('Brasileira', 'Brasileira'), ('Mediterrânea', 'Mediterranea'), ('Contemporânea', 'Contemporanea')], default='Árabe', max_length=15),
        ),
    ]
