# Generated by Django 3.2.4 on 2021-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cardapio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='categoria',
            field=models.CharField(choices=[(None, ''), ('Árabe', 'Arabe'), ('Oriental', 'Oriental'), ('Brasileira', 'Brasileira'), ('Mediterrânea', 'Mediterranea'), ('Contemporânea', 'Contemporanea')], max_length=15),
        ),
    ]
